### ISSUE TITLE
When I make edit map all area will gone / In rviz display map background are green

### ISSUE THREAD

**Issue by spygibas** [rbonghi/rosmapjs#2]
I'm not sure what problem Maybe value at ROSMAP.VALUE_UNWRITTEN ? or something problem on value

ROSMAP.VALUE_OBSTACLE = 100;
ROSMAP.VALUE_FREE_SPACE = 0;
ROSMAP.VALUE_UNKNOWN = -1;

That value working normal excerpt ROSMAP.VALUE_UNWRITTEN
PS. I use on ROS version NOETIC
Please help me these detail ros update new value or something else.

Thank you

**Comment by rbonghi** [comment]
Hi @spygibas ,

Thank you for your open issue, it's really a lot time a go when I wrote this javascript library. I honestly do not remember how it's works. I will check the first time possible :-)

**Comment by spygibas** [comment]
Hi @rbonghi  Thank you for you reply,Now I found solution, I get old data of map to push with new data edit it working.
