### ISSUE TITLE
how can i update the ros map

### ISSUE THREAD

**Issue by 252085814** [rbonghi/rosmapjs#3]
Hello, I am a novice, I would like to ask a question. How do I update the map files in the ROS system using Roslib? I see that the author posted ’/MAP_UPDATE‘ on the topic, should I subscribe to the topic in the ROS system? And what subsequent operations are required?

**Comment by rbonghi** [comment]
Hi @252085814,

This project is outdated and was working with ROS kinetic; unfortunately, I don't remember how it works.
I hope to update in a new ROS2 version.

Raffaello

**Comment by 252085814** [comment]
您的邮件已经收到，我会尽快查看的，感谢！辛苦了！
